class StageParams:
    PARAM_MD5 = "md5"
    PARAM_CMD = "cmd"
    PARAM_WDIR = "wdir"
    PARAM_DEPS = "deps"
    PARAM_OUTS = "outs"
    PARAM_LOCKED = "locked"
    PARAM_META = "meta"
    PARAM_ALWAYS_CHANGED = "always_changed"
    PARAM_PARAMS = "params"

    PARAM_OUTS_PERSIST = "outs_persist"
    PARAM_OUTS_PERSIST_NO_CACHE = "outs_persist_no_cache"
    PARAM_METRICS_NO_CACHE = "metrics_no_cache"
    PARAM_METRICS = "metrics"
    PARAM_OUTS_NO_CACHE = "outs_no_cache"
    PARAM_OUTS = "outs"
